name: check-up-to-dateness

description: Check whether a merge group PR is up to date relative to its base branch

inputs:
  token:
    description: GitHub token
    default: ${{ github.token }}

outputs:
  is-up-to-date:
    description: Whether the merge group PR is up to date relative to its base branch
    value: ${{ steps.main.outputs.is-up-to-date }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: |
        echo '${{ github.event.merge_group.head_commit.id }}'
        echo '${{ github.event.merge_group.head_commit.tree_id }}'
      shell: bash

    - id: main
      run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/run.sh"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
